/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Victor Cortez
 */
public class MenuPrinpal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public MenuPrinpal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        DesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jM_Categoria = new javax.swing.JMenuItem();
        jM_Menu = new javax.swing.JMenuItem();
        jM_Empleados = new javax.swing.JMenuItem();
        jM_Clientes = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DesktopPane.setBackground(new java.awt.Color(153, 255, 255));

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 813, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        jMenuItem6.setText("Salir");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Mantenimiento");

        jM_Categoria.setText("Categoria");
        jM_Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_CategoriaActionPerformed(evt);
            }
        });
        jMenu3.add(jM_Categoria);

        jM_Menu.setText("Menu");
        jM_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_MenuActionPerformed(evt);
            }
        });
        jMenu3.add(jM_Menu);

        jM_Empleados.setText("Empleados");
        jM_Empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_EmpleadosActionPerformed(evt);
            }
        });
        jMenu3.add(jM_Empleados);

        jM_Clientes.setText("Cliente");
        jM_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_ClientesActionPerformed(evt);
            }
        });
        jMenu3.add(jM_Clientes);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Consultas  ");

        jMenuItem1.setText(" Categoria");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem3.setText("Menu");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuItem4.setText("Empleados");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem5.setText("Clientes");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem7.setText("PedidoMesa");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jM_CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_CategoriaActionPerformed
        
        Categoria c;
        try {
            c = new Categoria();
            DesktopPane.add(c);
            c.show();
            c.setLocation(50,2);
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrinpal.class.getName()).log(Level.SEVERE, null, ex);
        }     
        
        
    }//GEN-LAST:event_jM_CategoriaActionPerformed

    private void jM_EmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_EmpleadosActionPerformed
       
        Empleados emp;
        try {
            emp = new Empleados();
            DesktopPane.add(emp);
            emp.show();
            emp.setLocation(50,2);
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrinpal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jM_EmpleadosActionPerformed

    private void jM_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_MenuActionPerformed
        try {
            Menu menu = new Menu();
            DesktopPane.add(menu);
            menu.show();
            menu.setLocation(50,2);
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrinpal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jM_MenuActionPerformed

   
    private void jM_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_ClientesActionPerformed
        try {
            Cliente cli = new Cliente();
            DesktopPane.add(cli);
            cli.show();
            cli.setLocation(50,2);
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrinpal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jM_ClientesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            consultarCategoria consul = new consultarCategoria();
            DesktopPane.add(consul);
            consul.show();
            consul.setLocation(50,2);
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrinpal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            consultaMenu conmenu = new consultaMenu();
            DesktopPane.add(conmenu);
            conmenu.show();
            conmenu.setLocation(50,2);
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrinpal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        try {
            consultaEmpleado conEmpleado = new consultaEmpleado();
            DesktopPane.add(conEmpleado);
            conEmpleado.show();
            conEmpleado.setLocation(50,2);
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrinpal.class.getName()).log(Level.SEVERE, null, ex);
        }
                                   
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        try {
            consultCliente concliente= new consultCliente();
            DesktopPane.add(concliente);
            concliente.show();
            concliente.setLocation(50,2);
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrinpal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
       
    this.dispose(); 
    System.exit( 0 );
 
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        try {
            Mesa m= new Mesa();
            DesktopPane.add(m);
            m.show();
            m.setLocation(50,2);
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrinpal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrinpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrinpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrinpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrinpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrinpal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JMenuItem jM_Categoria;
    private javax.swing.JMenuItem jM_Clientes;
    private javax.swing.JMenuItem jM_Empleados;
    private javax.swing.JMenuItem jM_Menu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    // End of variables declaration//GEN-END:variables
}
